  
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: image-registry
spec:
  type: image
  params:
    - name : url 
      value: registry.container-registry.svc.cluster.local:5000/randomquotes
